// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportReportAPI.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240806044425_dashboard")]
    partial class dashboard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SupportReportAPI.Models.CCNData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CCNData");
                });

            modelBuilder.Entity("SupportReportAPI.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ByValuePercentage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Percentage")
                        .HasColumnType("double");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("SupportReportAPI.Models.DashboardMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastDetectedProcess")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumberOfCCNsThisMonth")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfECNsThisMonth")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfManpowers")
                        .HasColumnType("int");

                    b.Property<int>("TotalBOMs")
                        .HasColumnType("int");

                    b.Property<int>("TotalDrawings")
                        .HasColumnType("int");

                    b.Property<int>("TotalProducts")
                        .HasColumnType("int");

                    b.Property<int>("TotalSLDs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DashboardMetrics");
                });

            modelBuilder.Entity("SupportReportAPI.Models.DonePO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobCategory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Outs")
                        .HasColumnType("int");

                    b.Property<double>("TProcess")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("DonePOs");
                });

            modelBuilder.Entity("SupportReportAPI.Models.ECNData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ECNData");
                });

            modelBuilder.Entity("SupportReportAPI.Models.EngineerSupport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Engineer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Requester")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupportDates")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EngineerSupports");
                });

            modelBuilder.Entity("SupportReportAPI.Models.EngineeringActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PIC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EngineeringActivities");
                });

            modelBuilder.Entity("SupportReportAPI.Models.EngineeringDetailProblem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cost")
                        .HasColumnType("double");

                    b.Property<string>("Cust")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DetailProblem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Engineering")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tgl")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EngineeringDetailProblems");
                });

            modelBuilder.Entity("SupportReportAPI.Models.OutstandingPostPO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DaysDeadline")
                        .HasColumnType("int");

                    b.Property<string>("DoneOuts")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OthersOuts")
                        .HasColumnType("int");

                    b.Property<int>("OthersProcess")
                        .HasColumnType("int");

                    b.Property<int>("PostPoOuts")
                        .HasColumnType("int");

                    b.Property<int>("PostPoProcess")
                        .HasColumnType("int");

                    b.Property<int>("PrePoOuts")
                        .HasColumnType("int");

                    b.Property<int>("PrePoProcess")
                        .HasColumnType("int");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalOuts")
                        .HasColumnType("int");

                    b.Property<int>("TotalProcess")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OutstandingPostPOs");
                });

            modelBuilder.Entity("SupportReportAPI.Models.SupportDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cust")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DetailProblem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Engineering")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tgl")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SupportDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
